"""Data models for the multi-agent system."""
from dataclasses import dataclass, field
from typing import Optional
from datetime import datetime


@dataclass
class TestRequirement:
    """Structured test requirement from Requirement Analyst."""
    test_objective: str = ""
    core_test_points: list = field(default_factory=list)
    exception_scenarios: list = field(default_factory=list)
    boundary_conditions: list = field(default_factory=list)

    def to_markdown(self) -> str:
        """Convert to markdown representation."""
        lines = [f"## 测试需求分析\n", f"**测试目标**: {self.test_objective}\n"]
        lines.append("### 核心测试点")
        for point in self.core_test_points:
            lines.append(f"- **{point.get('name', '')}**: {point.get('criteria', '')}")
        if self.exception_scenarios:
            lines.append("\n### 异常与边界场景")
            for s in self.exception_scenarios:
                lines.append(f"- {s}")
        if self.boundary_conditions:
            lines.append("\n### 边界条件")
            for c in self.boundary_conditions:
                lines.append(f"- {c}")
        return "\n".join(lines)


@dataclass
class CodeContext:
    """Code context extracted by Code Reader."""
    modules: list = field(default_factory=list)
    code_snippets: list = field(default_factory=list)
    dependencies: list = field(default_factory=list)
    api_endpoints: list = field(default_factory=list)
    logic_summary: str = ""

    def to_markdown(self) -> str:
        """Convert to markdown representation."""
        lines = ["## 代码逻辑分析\n"]
        if self.modules:
            lines.append("### 涉及模块")
            for m in self.modules:
                lines.append(f"- **{m.get('name', '')}** (`{m.get('path', '')}`)")
        if self.code_snippets:
            lines.append("\n### 核心代码片段")
            for s in self.code_snippets:
                lines.append(f"\n**{s.get('file', '')}** - {s.get('description', '')}")
                lines.append(f"```python\n{s.get('code', '')}\n```")
        if self.dependencies:
            lines.append("\n### 模块依赖")
            for d in self.dependencies:
                lines.append(f"- {d}")
        if self.api_endpoints:
            lines.append("\n### API 接口")
            for e in self.api_endpoints:
                lines.append(f"- `{e.get('method', '')} {e.get('path', '')}` - {e.get('description', '')}")
        if self.logic_summary:
            lines.append(f"\n### 逻辑解析\n{self.logic_summary}")
        return "\n".join(lines)


@dataclass
class TestScript:
    """Test script generated by Tester."""
    strategy: str = ""
    scripts: list = field(default_factory=list)
    dependencies: list = field(default_factory=list)
    notes: str = ""
    retry_count: int = 0
    sandbox_results: list = field(default_factory=list)

    def to_markdown(self) -> str:
        """Convert to markdown representation."""
        lines = ["## 测试用例与脚本\n"]
        if self.retry_count:
            lines.append(f"> 经过 {self.retry_count} 轮沙盒验证修复\n\n")
        if self.strategy:
            lines.append(f"### 测试策略\n{self.strategy}\n")
        if self.scripts:
            lines.append("### 测试脚本")
            for s in self.scripts:
                lines.append(f"\n#### {s.get('filename', '')}\n{s.get('description', '')}\n")
                lines.append(f"```python\n{s.get('code', '')}\n```")
        if self.dependencies:
            lines.append("\n### 依赖安装")
            lines.append("```bash")
            lines.append(f"pip install {' '.join(self.dependencies)}")
            lines.append("```")
        if self.notes:
            lines.append(f"\n### 备注\n{self.notes}")
        return "\n".join(lines)


@dataclass
class SecurityReview:
    """Security and architecture review from Reviewer."""
    high_risks: list = field(default_factory=list)
    code_smells: list = field(default_factory=list)
    architecture_assessment: str = ""

    def to_markdown(self) -> str:
        """Convert to markdown representation."""
        lines = ["## 安全与架构风险\n"]
        if self.high_risks:
            lines.append("### 🔴 高危漏洞")
            for r in self.high_risks:
                lines.append(f"\n**{r.get('title', '')}**")
                lines.append(f"- 问题: {r.get('description', '')}")
                lines.append(f"- 修复: {r.get('fix', '')}")
        if self.code_smells:
            lines.append("\n### 🟡 代码异味")
            for s in self.code_smells:
                lines.append(f"\n**{s.get('title', '')}**")
                lines.append(f"- 问题: {s.get('description', '')}")
                lines.append(f"- 建议: {s.get('suggestion', '')}")
        if self.architecture_assessment:
            lines.append(f"\n### 🏗️ 架构评估\n{self.architecture_assessment}")
        return "\n".join(lines)


@dataclass
class ReviewReport:
    """Final comprehensive report combining all agent outputs."""
    repo_url: str = ""
    requirement: TestRequirement = None
    code_context: CodeContext = None
    test_script: TestScript = None
    security_review: SecurityReview = None
    token_usage: dict = None
    generated_at: str = ""

    def __post_init__(self):
        if self.requirement is None:
            self.requirement = TestRequirement()
        if self.code_context is None:
            self.code_context = CodeContext()
        if self.test_script is None:
            self.test_script = TestScript()
        if self.security_review is None:
            self.security_review = SecurityReview()
        if self.token_usage is None:
            self.token_usage = {"prompt_tokens": 0, "completion_tokens": 0, "total_tokens": 0}
        if not self.generated_at:
            self.generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    def to_markdown(self) -> str:
        """Generate full markdown report."""
        lines = [
            f"# 综合测试与优化报告\n",
            f"**仓库**: {self.repo_url}  ",
            f"**生成时间**: {self.generated_at}\n",
            "---\n",
            self.requirement.to_markdown(),
            "\n---\n",
            self.code_context.to_markdown(),
            "\n---\n",
            self.test_script.to_markdown(),
            "\n---\n",
            self.security_review.to_markdown(),
        ]
        return "\n".join(lines)

    def to_dict(self) -> dict:
        """Convert to dictionary for JSON serialization."""
        return {
            "repo_url": self.repo_url,
            "generated_at": self.generated_at,
            "token_usage": self.token_usage,
            "requirement": {
                "test_objective": self.requirement.test_objective,
                "core_test_points": self.requirement.core_test_points,
                "exception_scenarios": self.requirement.exception_scenarios,
                "boundary_conditions": self.requirement.boundary_conditions,
            },
            "code_context": {
                "modules": self.code_context.modules,
                "code_snippets": self.code_context.code_snippets,
                "dependencies": self.code_context.dependencies,
                "api_endpoints": self.code_context.api_endpoints,
                "logic_summary": self.code_context.logic_summary,
            },
            "test_script": {
                "strategy": self.test_script.strategy,
                "scripts": self.test_script.scripts,
                "dependencies": self.test_script.dependencies,
                "notes": self.test_script.notes,
                "retry_count": self.test_script.retry_count,
            },
            "security_review": {
                "high_risks": self.security_review.high_risks,
                "code_smells": self.security_review.code_smells,
                "architecture_assessment": self.security_review.architecture_assessment,
            },
        }
